---
name: Hosts
rest_endpoint: /api/fmc_config/v1/domain/{DOMAIN_UUID}/object/hosts
res_description: >-
  This plural resource manages a bulk of Hosts.
  The FMC API supports quick bulk creation of this resource. Deletion of this resource is done one-by-one or in bulk, depending of FMC version. Modification is always done one-by-one.
  Updating/deleting `fmc_hosts` can thus take much more time than creating it
doc_category: Objects
is_bulk: true
minimum_version_bulk_delete: "7.4"
attributes:
  - model_name: items
    type: Map
    description: >-
      Map of hosts. The key of the map is the name of the individual Host. Renaming Hosts in bulk
      is not yet implemented.
    map_key_example: hosts_1
    mandatory: true
    attributes:
      - model_name: id
        type: String
        resource_id: true
        description: UUID of the managed Host.
        exclude_example: true
        exclude_test: true
      - model_name: description
        type: String
        description: Optional user-created description.
        example: "My Host 1"
      - model_name: overridable
        type: Bool
        description: Indicates whether object values can be overridden.
        exclude_example: true
        example: "true"
      - model_name: value
        tf_name: ip
        type: String
        mandatory: true
        description: IP of the host.
        example: 10.1.1.1
      - model_name: type
        type: String
        description: Type of the object; this value is always 'Host'.
        computed: true
