// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

//template:end imports

//template:begin testAccDataSource
func TestAccDataSourceFmcDevice(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.fmc_device.test", "name", "FTD1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.fmc_device.test", "host_name", "192.168.0.152"))
	checks = append(checks, resource.TestCheckResourceAttr("data.fmc_device.test", "reg_key", "cisco"))
	checks = append(checks, resource.TestCheckResourceAttr("data.fmc_device.test", "license_caps.0", "MALWARE"))
	checks = append(checks, resource.TestCheckResourceAttr("data.fmc_device.test", "access_policy_id", "9BCD876543456789A0"))
	checks = append(checks, resource.TestCheckResourceAttr("data.fmc_device.test", "access_policy_name", "Test-ACP"))
	checks = append(checks, resource.TestCheckResourceAttr("data.fmc_device.test", "type", "Device"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceFmcDeviceConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

//template:end testAccDataSource

//template:begin testPrerequisites
//template:end testPrerequisites

//template:begin testAccDataSourceConfig
func testAccDataSourceFmcDeviceConfig() string {
	config := `resource "fmc_device" "test" {` + "\n"
	config += `	name = "FTD1"` + "\n"
	config += `	host_name = "192.168.0.152"` + "\n"
	config += `	reg_key = "cisco"` + "\n"
	config += `	license_caps = ["MALWARE"]` + "\n"
	config += `	access_policy_id = "9BCD876543456789A0"` + "\n"
	config += `	access_policy_name = "Test-ACP"` + "\n"
	config += `	type = "Device"` + "\n"
	config += `}` + "\n"

	config += `
		data "fmc_device" "test" {
			id = fmc_device.test.id
		}
	`
	return config
}

//template:end testAccDataSourceConfig
