// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

//template:end imports

//template:begin types
type PhysicalInterface struct {
	Id             types.String `tfsdk:"id"`
	Domain         types.String `tfsdk:"domain"`
	DeviceId       types.String `tfsdk:"device_id"`
	PhyInterfaceId types.String `tfsdk:"phy_interface_id"`
	Enabled        types.Bool   `tfsdk:"enabled"`
	Mode           types.String `tfsdk:"mode"`
	Name           types.String `tfsdk:"name"`
	Ifname         types.String `tfsdk:"ifname"`
}

//template:end types

//template:begin getPath
func (data PhysicalInterface) getPath() string {
	return fmt.Sprintf("/api/fmc_config/v1/domain/{DOMAIN_UUID}/devices/devicerecords/%v/physicalinterfaces/%v", data.DeviceId.ValueString(), data.PhyInterfaceId.ValueString())
}

//template:end getPath

//template:begin toBody
func (data PhysicalInterface) toBody(ctx context.Context, state PhysicalInterface) string {
	body := ""
	if data.Id.ValueString() != "" {
		body, _ = sjson.Set(body, "id", data.Id.ValueString())
	}
	if state.PhyInterfaceId.ValueString() != "" {
		body, _ = sjson.Set(body, "id", state.PhyInterfaceId.ValueString())
	}
	if !data.Enabled.IsNull() {
		body, _ = sjson.Set(body, "enabled", data.Enabled.ValueBool())
	}
	if !data.Mode.IsNull() {
		body, _ = sjson.Set(body, "mode", data.Mode.ValueString())
	}
	if !data.Name.IsNull() {
		body, _ = sjson.Set(body, "name", data.Name.ValueString())
	}
	body, _ = sjson.Set(body, "type", "PhysicalInterface")
	if !data.Ifname.IsNull() {
		body, _ = sjson.Set(body, "ifname", data.Ifname.ValueString())
	}
	return body
}

//template:end toBody

//template:begin fromBody
func (data *PhysicalInterface) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("enabled"); value.Exists() {
		data.Enabled = types.BoolValue(value.Bool())
	} else {
		data.Enabled = types.BoolValue(true)
	}
	if value := res.Get("mode"); value.Exists() {
		data.Mode = types.StringValue(value.String())
	} else {
		data.Mode = types.StringNull()
	}
	if value := res.Get("name"); value.Exists() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("ifname"); value.Exists() {
		data.Ifname = types.StringValue(value.String())
	} else {
		data.Ifname = types.StringNull()
	}
}

//template:end fromBody

//template:begin updateFromBody
func (data *PhysicalInterface) updateFromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("enabled"); value.Exists() && !data.Enabled.IsNull() {
		data.Enabled = types.BoolValue(value.Bool())
	} else if data.Enabled.ValueBool() != true {
		data.Enabled = types.BoolNull()
	}
	if value := res.Get("mode"); value.Exists() && !data.Mode.IsNull() {
		data.Mode = types.StringValue(value.String())
	} else {
		data.Mode = types.StringNull()
	}
	if value := res.Get("name"); value.Exists() && !data.Name.IsNull() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("ifname"); value.Exists() && !data.Ifname.IsNull() {
		data.Ifname = types.StringValue(value.String())
	} else {
		data.Ifname = types.StringNull()
	}
}

//template:end updateFromBody

//template:begin isNull
func (data *PhysicalInterface) isNull(ctx context.Context, res gjson.Result) bool {
	if !data.DeviceId.IsNull() {
		return false
	}
	if !data.PhyInterfaceId.IsNull() {
		return false
	}
	if !data.Enabled.IsNull() {
		return false
	}
	if !data.Mode.IsNull() {
		return false
	}
	if !data.Name.IsNull() {
		return false
	}
	if !data.Ifname.IsNull() {
		return false
	}
	return true
}

//template:end isNull
