// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

//template:end imports

//template:begin testAcc
func TestAccFmcPhysicalInterface(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("fmc_physicalinterface.test", "device_id", "<Device_ID>"))
	checks = append(checks, resource.TestCheckResourceAttr("fmc_physicalinterface.test", "enabled", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("fmc_physicalinterface.test", "mode", "NONE"))
	checks = append(checks, resource.TestCheckResourceAttr("fmc_physicalinterface.test", "name", "GigabitEthernet0/1"))
	checks = append(checks, resource.TestCheckResourceAttr("fmc_physicalinterface.test", "ifname", "interface_name"))

	var steps []resource.TestStep
	if os.Getenv("SKIP_MINIMUM_TEST") == "" {
		steps = append(steps, resource.TestStep{
			Config: testAccFmcPhysicalInterfaceConfig_minimum(),
		})
	}
	steps = append(steps, resource.TestStep{
		Config: testAccFmcPhysicalInterfaceConfig_all(),
		Check:  resource.ComposeTestCheckFunc(checks...),
	})

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps:                    steps,
	})
}

//template:end testAcc

//template:begin testPrerequisites
//template:end testPrerequisites

//template:begin testAccConfigMinimal
func testAccFmcPhysicalInterfaceConfig_minimum() string {
	config := `resource "fmc_physicalinterface" "test" {` + "\n"
	config += `	device_id = "<Device_ID>"` + "\n"
	config += `	phy_interface_id = "<PhysinterID>"` + "\n"
	config += `	mode = "NONE"` + "\n"
	config += `}` + "\n"
	return config
}

//template:end testAccConfigMinimal

//template:begin testAccConfigAll
func testAccFmcPhysicalInterfaceConfig_all() string {
	config := `resource "fmc_physicalinterface" "test" {` + "\n"
	config += `	device_id = "<Device_ID>"` + "\n"
	config += `	enabled = true` + "\n"
	config += `	mode = "NONE"` + "\n"
	config += `	name = "GigabitEthernet0/1"` + "\n"
	config += `	ifname = "interface_name"` + "\n"
	config += `}` + "\n"
	return config
}

//template:end testAccConfigAll
