// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

//template:end imports

//template:begin testAcc
func TestAccFmcDevice(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("fmc_device.test", "name", "FTD1"))
	checks = append(checks, resource.TestCheckResourceAttr("fmc_device.test", "host_name", "192.168.0.152"))
	checks = append(checks, resource.TestCheckResourceAttr("fmc_device.test", "reg_key", "cisco"))
	checks = append(checks, resource.TestCheckResourceAttr("fmc_device.test", "license_caps.0", "MALWARE"))
	checks = append(checks, resource.TestCheckResourceAttr("fmc_device.test", "access_policy_id", "9BCD876543456789A0"))
	checks = append(checks, resource.TestCheckResourceAttr("fmc_device.test", "access_policy_name", "Test-ACP"))
	checks = append(checks, resource.TestCheckResourceAttr("fmc_device.test", "type", "Device"))

	var steps []resource.TestStep
	if os.Getenv("SKIP_MINIMUM_TEST") == "" {
		steps = append(steps, resource.TestStep{
			Config: testAccFmcDeviceConfig_minimum(),
		})
	}
	steps = append(steps, resource.TestStep{
		Config: testAccFmcDeviceConfig_all(),
		Check:  resource.ComposeTestCheckFunc(checks...),
	})
	steps = append(steps, resource.TestStep{
		ResourceName: "fmc_device.test",
		ImportState:  true,
	})

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps:                    steps,
	})
}

//template:end testAcc

//template:begin testPrerequisites
//template:end testPrerequisites

//template:begin testAccConfigMinimal
func testAccFmcDeviceConfig_minimum() string {
	config := `resource "fmc_device" "test" {` + "\n"
	config += `	host_name = "192.168.0.152"` + "\n"
	config += `	reg_key = "cisco"` + "\n"
	config += `	access_policy_id = "9BCD876543456789A0"` + "\n"
	config += `}` + "\n"
	return config
}

//template:end testAccConfigMinimal

//template:begin testAccConfigAll
func testAccFmcDeviceConfig_all() string {
	config := `resource "fmc_device" "test" {` + "\n"
	config += `	name = "FTD1"` + "\n"
	config += `	host_name = "192.168.0.152"` + "\n"
	config += `	reg_key = "cisco"` + "\n"
	config += `	license_caps = ["MALWARE"]` + "\n"
	config += `	access_policy_id = "9BCD876543456789A0"` + "\n"
	config += `	access_policy_name = "Test-ACP"` + "\n"
	config += `	type = "Device"` + "\n"
	config += `}` + "\n"
	return config
}

//template:end testAccConfigAll
